local nav = dofile(SCRIPT_DIR .. "/nav.lua")
local qt = QML_Tester()
qt:wait(800)
-- drop an obstacle wall (right clicks), then command a target (left click)
qt:click(275, 420, "right")
qt:click(275, 450, "right")
qt:click(275, 480, "right")
qt:click(275, 510, "right")
qt:wait(400)
qt:screenshot("/tmp/nav_before.png")
qt:click(400, 200) -- target
qt:wait(1200)
qt:screenshot("/tmp/nav_path.png")
qt:wait(4000)
qt:screenshot("/tmp/nav_driving.png")
shutdown()
